feat(about-page): generalize button component and clean up buttons
up-csi/up-csi.github.io pull request #100
Opened 2024-11-25 18:10 UTC by LantingKurt

Generalized the Button component to use <a> tags and applied the changes across the site. Updated the buttons in the About page to link properly, setting the href to # for Event and Project pages for now.

2024-11-26 06:40 UTC, BastiDood requested changes
Just a few nitpicks here that I wanna note since the new Svelte 5 run syntax introduces nicer patterns.

2024-11-26 06:40 UTC, BastiDood commented on src/lib/components/LinkButton.svelte
I'd like to suggest extending the `HTMLAnchorAttributes` from `svelte/elements` here so that we can spread the `<a>` props to the internal one.

```svelte
<script lang="ts>
    import type { HTMLAnchorAttributes } from 'svelte/elements';
    import type { Snippet } from 'svelte';

    interface Props extends HTMLAnchorAttributes {
        children?: Snippet;
    }

    const { children, ...rest }: Props = $props;
</script>

<a {...rest} class="...">{@render children?.()}</a>
```

2024-12-02 05:50 UTC, LantingKurt commented on src/lib/components/LinkButton.svelte
Noted! Thank you for the suggestion :)

2024-12-18 02:17 UTC, VeeIsForVanana approved these changes
LGTM! 🚀🚀🚀

2024-12-18 07:34 UTC, merged