feat(src): add General FAQ dropdown component to Projects page
up-csi/up-csi.github.io pull request #105
Opened 2024-12-19 15:58 UTC by Pandannnnn

This PR addresses [#102.](https://github.com/up-csi/up-csi.github.io/issues/102)

Summary of Changes:

- Create FAQ.svelte at src/lib/components
- Add implemented General FAQ from FAQ.svelte to projects page.

Points for improvement:

- [ ] Better coding style (avoid repetitiveness and improve readability)
- [ ] Add more flexibility to the container
- [ ] Add more features to the General FAQ

2024-12-22 05:21 UTC, ehrelevant requested changes
Thank you for the contribution and congratulations for your first PR to this repository! I included a few comments and some suggestions on improvements that could be made on the implementation. Also, as good as small and atomic commits are, I think this might be a bit too much, though that might just be me. Still, I do appreciate the extra effort in doing many small commits like this. Actually, @VeeIsForVictor any opinions on this? 

Well, all that aside, good work on your implementation and well done on the responsive styling!

2025-01-22 11:29 UTC, ehrelevant commented on src/lib/components/FAQ.svelte
> +    </div>
In retrospect, I retract this suggestion, this wouldn't have worked if it was in the same file (`FAQ.svelte`). My bad about this one. That said, putting it in a separate file wouldn't have been a bad idea, i.e. `FaqEntry.svelte`, but I suppose it might be file bloat.

2025-01-22 12:11 UTC, ehrelevant requested changes
This ended up not really being a review anymore, but would like to hear your thoughts on these suggestions @VeeIsForVictor. In short, I feel like using an array and looping for a likely small number of elements is unnecessary. Though, again, I'm wondering if it's really worth thinking about this too heavily given this isn't a component that is likely to be reused elsewhere. Anyways, thanks for the refactor!

2025-01-22 12:11 UTC, ehrelevant commented on src/routes/projects/+page.svelte
> +    ]
I think a possible alternative approach is to instead consider the `Faq` component as a sort of styled "list" (i.e. `<ol>`/`<ul>`) which we fill up with styled "list items" (i.e. `<li>`). In that sense, maybe we can create `FaqEntry.svelte` or `GenFaqEntry.svelte` file containing the looped block. 

```svelte
<!-- FaqEntry.svelte -->
<script lang="ts">
    import type { Snippet } from 'svelte';

    interface Props {
        title: string; // This could also be a Snippet
        children?: Snippet;
    }
    const { title, children }: Props = $props();
</script>

<div class="max-w-md text-center md:w-1/2">
    <h2 class="prose mb-2 text-2xl font-bold dark:prose-invert md:text-lg">{title}</h2>
    <div class="prose text-justify text-sm leading-relaxed dark:prose-invert md:text-base">
        {@render children?.()}
    </div>
</div>
```

Then use the `Faq.svelte` as just a styled layout element.

```svelte
<!-- Faq.svelte -->
<script lang="ts">
    import type { Snippet } from 'svelte';

    interface Props {
        children?: Snippet;
    }
    const { children }: Props = $props();
</script>

<div
    class="container mx-auto flex flex-col items-center gap-8 px-20 md:flex-row md:justify-between"
>
    {@render children?.()}
</div>
```
What do you think about this approach?

2025-01-22 12:15 UTC, ehrelevant commented on src/routes/projects/+page.svelte
> +    ]
For reference, this will end up with things looking like this in `projects/+page.svelte`:

```svelte
<Faq>
    <FaqEntry title="GENERAL FAQ">
        <span
            >Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
            exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</span
        >
    </FaqEntry>
    <FaqEntry title="GENERAL FAQ">
        <span
            >Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
            exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</span
        >
    </FaqEntry>
</Faq>
```

2025-01-22 22:08 UTC, VeeIsForVictor commented on src/routes/projects/+page.svelte
> +    ]
Ah, this is a much better implementation that is a lot cleaner than the rough one I came up with. Thanks!

2025-01-22 22:24 UTC, VeeIsForVictor commented on src/routes/projects/+page.svelte
> +<Faq {faqEntries}/>
Disregarding this since we're abandoning the old implementation.

2025-01-23 02:06 UTC, ehrelevant approved these changes
LGTM!!

2025-01-24 05:24 UTC, merged