feat: adjust content container styling
up-csi/up-csi.github.io pull request #45
Opened 2024-03-22 05:32 UTC by galierie

This PR adjusts the styling of the content container component to better fit the website figma. Note that the background colors for the containers are not yet working but are already formatted according to Tailwind's one-off arbitrary value specs; as such, the background colors for now are csi-white and csi-black for light and dark mode, respectively.

2024-03-22 06:00 UTC, BastiDood requested changes

2024-03-22 06:00 UTC, BastiDood commented on src/lib/components/ContentContainer.svelte
> +    class="flex flex-col items-center justify-between gap-12 rounded-3xl bg-[#f6f6f6] px-8 py-8 md:px-32 md:py-16 xl:flex-row dark:bg-[#1d1d1d]"
Let's edit the `tailwind.config.js` so that these hard-coded numbers are in the configuration itself.

2024-03-22 15:27 UTC, BastiDood requested changes
One more change to go. Note that this may involve editing more than one file in the entire codebase.

2024-03-22 15:27 UTC, BastiDood commented on tailwind.config.js
It would be nice to have [color stops](https://tailwindcss.com/docs/customizing-colors#color-object-syntax) here instead of explicit color names. Feel free to check out [UIColors](https://uicolors.app/create) to help automate the process. Let's aim for hex colors that are as similar as possible to the original design.

2024-04-01 03:26 UTC, galierie commented
uhhhh nyarks

2024-04-01 05:02 UTC, BastiDood approved these changes
Awesome! Great work on the color stops. LGTM! 🚀

2024-04-01 05:02 UTC, merged